<?php
$product = $block->getViewModel()->getProductDataUsingSku();
if($product){
?>

<div class="featured">
        <div class="featured__img">
                <img src="./media/catalog/product/<?= $product->getData('image')?>" alt="<?= $product->getName(); ?>" width="450">
        </div>
        <div class="featured__content">
                <span class="featured__name"><?= $product->getName(); ?></span>
                <span class="featured__price">£<?= number_format($product->getData('price'),2); ?></span>
                <div class="featured__desc"><?= $product->getData('description');?></div>
                <a class="featured__link" href="/<?= $product->getData('url_key'); ?>">View Product &rsaquo;</a>
        </div>
</div>

<?php } ?>